config/routes.rb
Rails.application.routes.draw do
  resource :session, only: %i[new show create destroy]
  resources :admins, only: %i[index show new create edit update destroy]
  resources :books, only: %i[index show new edit create update destroy]
  resources :genres, only: %i[index show new edit create update destroy]
  resources :authors, only: %i[index show new edit create update destroy]
  root 'books#index'
end

app/models/admin.rb
class Admin < ApplicationRecord
  enum role: { basic: 0, book_admin: 1, genre_admin: 2, super_admin: 3 }, _suffix: :role
  has_secure_password
  validates :role, presence: true
  validates :password_digest, presence: true
  validates :name, presence: true
  validates :email, presence: true, format: { with: /\A[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]+\z/ ,
                                              message: 'Invalid e-mail! Please provide a valid e-mail address'}, uniqueness: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :book_authors
  has_many :books, through: :book_authors

  validates :name, presence: true
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :picture
  has_many :book_authors
  has_many :authors, through: :book_authors
  belongs_to :genre, optional: true

  validates :name, presence: true
  validates :author_ids, presence: true
end

app/models/book_author.rb
class BookAuthor < ApplicationRecord
  belongs_to :book
  belongs_to :author
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :books

  validates :name, presence: true
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  before_action :require_authentication
  before_action :authorize_admin!
  before_action :set_admin!, only: %i[edit update destroy]

  def index
    @admins = Admin.all
  end

  def new
    @admin = Admin.new
    @roles = Admin.roles.keys
  end

  def edit
    @roles = Admin.roles.keys
  end

  def update
    if @admin.update admin_params
      redirect_to admins_path
    else
      render :edit
    end
  end

  def create
    @admin = Admin.new admin_params

    if @admin.save
      redirect_to admins_path
    else
      render :new
    end
  end

  def destroy
    @admin.destroy
    redirect_to admins_path
  end

  private

  def admin_params
    params.require(:admin).permit(:email, :name, :role, :password, :password_confirmation)
  end

  def set_admin!
    @admin = Admin.find params[:id]
  end

  def authorize_admin!
    authorize(@admin || Admin)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authorization
  include Authentication
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :require_authentication, except: %i[show index]
  before_action :authorize_author!
  before_action :set_author!, only: %i[show destroy edit update]
  after_action :verify_authorized, except: %i[show index]

  def index
    @authors = Author.all
  end

  def new
    @author = Author.new
  end

  def create
    @author = Author.new author_params

    if @author.save
      redirect_to authors_path
    else
      render authors_new_path
    end
  end

  def update
    if @author.update author_params
      redirect_to authors_path
    else
      render authors_id_path
    end
  end

  def show
    @book = Book.all
  end

  def edit
    @book_author = BookAuthor.new
    @book = Book.all
  end

  def destroy
    @author.destroy
    redirect_to authors_path
  end

  private

  def authorize_author!
    authorize(@author || Author)
  end

  def set_author!
    @author = Author.find_by id: params[:id]
  end

  def author_params
    params.require(:author).permit(:name, book_ids: [])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :require_authentication, except: %i[show index]
  before_action :authorize_book!
  after_action :verify_authorized, except: %i[show index]
  before_action :fetch_authors, only: %i[new edit show]
  before_action :set_book!, only: %i[show destroy edit update]

  def destroy
    @book.destroy
    redirect_to books_path
  end

  def edit
    @book_author = BookAuthor.new
    @genres = Genre.all
  end

  def update
    if @book.update book_params
      redirect_to books_path
    else
      render books_id_path
    end
  end

  def index
    @books_by_genres = Genre.includes(:books).map do |genre|
      { name: genre.name, books: genre.books }
    end

    @books_by_genres.push({ name: "Books without a genre:", books: Book.where(genre_id: nil) })
  end

  def show
    @authors = Author.all
    @genres = Genre.all
  end

  def new
    @book = Book.new
    @book_author = BookAuthor.new
    @genres = Genre.all
  end

  def create
    @book = Book.new book_params

    if @book.save
      redirect_to books_path
    else
      render new_book_path
    end
  end

  private

  def book_params
    params.require(:book).permit(:name, :genre_id, :picture, author_ids: [])
  end

  def set_book!
    @book = Book.find params[:id]
  end

  def fetch_authors
    @authors = Author.all
  end

  def authorize_book!
    authorize(@book || Book)
  end
end

app/controllers/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern

  included do
    private

    def current_user
      @current_user ||= Admin.find_by(id: session[:admin_id]) if session[:admin_id].present?
    end

    def user_signed_in?
      current_user.present?
    end

    def require_authentication
      return if user_signed_in?
      redirect_to books_path
    end

    def require_no_authentication
      return if !user_signed_in?
      redirect_to books_path
    end

    def sign_in(user)
      session[:admin_id] = user.id
    end

    def sign_out
      session.delete :admin_id
    end

    helper_method :current_user, :user_signed_in?
  end
end

app/controllers/concerns/authorization.rb
module Authorization
  extend ActiveSupport::Concern

  included do 
    include Pundit

    rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

    private

    def user_not_authorized
    	redirect_to(request.referer || root_path)
    end
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :require_authentication, except: %i[show index]
  before_action :authorize_genre!
  before_action :set_genre!, only: %i[show destroy edit update]
  after_action :verify_authorized, except: %i[show index]

  def index
    @genres = Genre.all
  end

  def show
    @books = Book.all
  end

  def new
    @genre = Genre.new
    @book = Book.new
  end

  def create
    @books = Book.all
    @genre = Genre.new genre_params

    if @genre.save
      redirect_to genres_path
    else
      redirect_to genres_new_path
    end
  end

  def edit
    @books = Book.all
  end

  def update
    if @genre.update genre_params
      redirect_to genres_path
    else
      render genres_id_path
    end
  end

  def destroy
    @genre.destroy
    redirect_to genres_path
  end

  private

  def set_genre!
    @genre = Genre.find params[:id]
  end

  def genre_params
    params.require(:genre).permit(:name, book_ids: [])
  end

  def genre_name
    params.require(:genre).permit(:name)
  end

  def authorize_genre!
    authorize(@genre || Genre)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :require_no_authentication, only: %i[new create]
  before_action :require_authentication, only: :destroy

  def new
  end

  def create
    admin = Admin.find_by email: params[:email]

    if admin&.authenticate(params[:password])
      sign_in admin
      redirect_to books_path
    else
      redirect_to new_session_path
    end
  end

  def destroy
    sign_out
    redirect_to books_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def nav_tab(title, url, options = {})
    current_page = options.delete :current_page

    css_class = current_page == title ? 'text-secondary' : 'text-white'

    options[:class] = if options[:class]
      options[:class] + ' ' + css_class
    else
      css_class
    end

    link_to title, url, options
  end

  def currently_at(current_page = '')
    render partial: 'shared/menu', locals: {current_page: current_page}
  end

  def full_title(page_title = "")
    base_title ="Library"
    if page_title.present?
      "#{page_title} | #{base_title}"
    else
      base_title
    end
  end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/admins/_form.html.erb
<%= form_with model: @admin do |f| %>
  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :email %>
    </div>
    <div class="col-sm-10">
      <%= f.email_field :email, placeholder: 'E-mail', required: true, class: 'form-control form-control-lg' %>
    </div>
  </div>
  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :name %>
    </div>
    <div class="col-sm-10">
      <%= f.text_field :name, placeholder: 'Name', required: true, class: 'form-control form-control-lg' %>
    </div>
  </div>
  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :password %>
    </div>
    <div class="col-sm-10">
      <%= f.password_field :password, required: true, class: 'form-control form-control-lg' %>
    </div>
  </div>
  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :password_confirmation %>
    </div>
    <div class="col-sm-10">
      <%= f.password_field :password_confirmation, required: true, class: 'form-control form-control-lg' %>
    </div>
  </div>
  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :role %>
    </div>
    <div class="col-sm-10">
      <%= f.select :role, @roles, {}, class: 'form-select form-select-lg' %>
    </div>
  </div>
  <%= f.submit "Register ", class: 'btn btn-primary btn-lg' %>
<% end %>

app/views/admins/edit.html.erb
<% provide :page_title, 'Admins' %>
<% currently_at 'Admins' %>
<div class="container-sm">
  <h1 class="mb-4">Edit admin </h1>
  <%= form_with model: @admin do |f| %>
    <div class="mb-3 row">
      <div class="col-sm-2 col-form-label">
        <%= f.label :email %>
      </div>
      <div class="col-sm-10">
        <%= f.email_field :email, placeholder: 'E-mail', class: 'form-control form-control-lg' %>
      </div>
    </div>
    <div class="mb-3 row">
      <div class="col-sm-2 col-form-label">
        <%= f.label :name %>
      </div>
      <div class="col-sm-10">
        <%= f.text_field :name, placeholder: 'Name', class: 'form-control form-control-lg' %>
      </div>
    </div>
    <div class="mb-3 row">
      <div class="col-sm-2 col-form-label">
        <%= f.label :password %>
      </div>
      <div class="col-sm-10">
        <%= f.password_field :password, class: 'form-control form-control-lg' %>
      </div>
    </div>
    <div class="mb-3 row">
      <div class="col-sm-2 col-form-label">
        <%= f.label :password_confirmation %>
      </div>
      <div class="col-sm-10">
        <%= f.password_field :password_confirmation, class: 'form-control form-control-lg' %>
      </div>
    </div>
    <div class="mb-3 row">
      <div class="col-sm-2 col-form-label">
        <%= f.label :role %>
      </div>
      <div class="col-sm-10">
        <%= f.select :role, @roles, {}, class: 'form-select form-select-lg' %>
      </div>
    </div>
    <%= f.submit "Edit", class: 'btn btn-primary btn-lg' %>
  <% end %>
</div>

app/views/admins/index.html.erb
<% provide :page_title, 'Admins' %>
<% currently_at 'Admins' %>
<h1 class="mb-4">Admins:</h1>
<div class="row row-cols-1 row-cols-md-5 g-4 mb-4">
  <% @admins.each do |admin| %>
    <div class="col">
      <div class="card" style="width: 300px;">
        <h2 class="mb-2 card-header"><%= admin.name %></h2>
        <div class="mb-1 card-body">
          <div class="mb-2">
            <div>Email: <%= admin.email %></div>
            <div>Role: <%= admin.role.humanize %></div>
          </div>
          <%= link_to "Edit",  edit_admin_path(admin), class: 'btn btn-secondary btn-sm', :method => :get %>
          <%= link_to "Destroy", admin_path(admin), class: 'btn btn-danger btn-sm', data: {method: :delete, confirm: "Are you sure?"} %>
        </div>
      </div>
    </div>
  <% end %>
</div>
<%= button_to "Add new admin", new_admin_path, :id => "open-contacts-dialog-btn",
          :class => 'btn btn-primary btn-md', :method => :get %>

app/views/admins/new.html.erb
<% provide :page_title, 'Registration' %>
<% currently_at 'Sign Up' %>
<h1 class="mb-4">Registration</h1>
<%= render 'form' %>

app/views/authors/edit.html.erb
<% currently_at 'Authors' %>
<div class="container-sm">
  <h1 class="mb-4">Edit authors</h1>
  <%= form_tag author_path(@author), method: :put do %>
    <div class="mb-3 row">
      <div class="col-sm-2 col-form-label">
        <label for = "author_name">Author name:</label>
      </div>
      <div class="col-sm-10">
        <%= text_field 'author', 'name', required: true, class: 'form-control form-control-lg' %>
      </div>
    </div>
    <div class="mb-3 row">
      <div class="col-sm-2 col-form-label">
        <label for = "book_ids">Books:</label>
      </div>
      <div class="col-sm-10">
        <%= collection_select(:author, :book_ids, @book, :id, :name, {}, {multiple: true, class: 'form-select form-select-lg'}) %>
      </div>
    </div>
    <%= submit_tag "Update", class: 'btn btn-primary btn-md' %>
  <% end %>
</div>

app/views/authors/index.html.erb
<% provide :page_title, 'Authors' %>
<% currently_at 'Authors' %>
<h1 class="mb-4">Authors:</h1>
<div class="row row-cols-1 row-cols-md-5 g-4 mb-4">
  <% @authors.each do |author| %>
    <div class="col">
      <div class="card" style="width: 300px;">
        <h2 class="mb-4 card-header"><%= author.name %></h2>
        <div class="card-body">
          <%= link_to "Show", author_path(author), class: 'btn btn-secondary btn-sm', :method => :get %>
          <% if policy(author).edit? %>
            <%= link_to "Edit", edit_author_path(author), class: 'btn btn-secondary btn-sm', :method => :get %>
          <% end %>
          <% if policy(author).destroy? %>
            <%= link_to "Destroy", author_path(author), class: 'btn btn-danger btn-sm', data: {method: :delete, confirm: "Are you sure?"} %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>
<% if policy(@authors).create? %>
  <%= button_to "Add new author", new_author_path, :id => 'open-contacts-dialog-btn',
  class: 'btn btn-primary', :method => :get %>
<% end %>

app/views/authors/new.html.erb
<% currently_at 'Authors' %>
<div class="container-sm">
  <h1 class="mb-4">New author</h1>
  <%= form_tag({:action => 'create'}, multipart: true) do %>
    <div class="mb-3 row">
      <div class="col-sm-2 col-form-label">
        <label for = "author_name">Author name:</label>
      </div>
      <div class="col-sm-5">
        <%= text_field 'author', 'name', required: true, class: 'form-control form-control-lg' %>
      </div>
    </div>
    <%= submit_tag "Create", class: 'btn btn-primary btn-md' %>
  <% end %>
</div>

app/views/authors/show.html.erb
<% currently_at 'Authors' %>
<h1 class="mb-4"><%= @author.name%></h1>
<h2 class="mb-4">Books:
  <%= @author.books.map { |book| link_to book.name, book }.join(', ').html_safe %>
</h2>

app/views/books/edit.html.erb
<% currently_at 'Home' %>
<div class="container-sm">
  <h1 class="mb-4">Edit book</h1>
  <%= form_tag book_path(@book), method: :put, multipart: true do %>
    <div class="mb-3 row">
      <div class="col-sm-2 col-form-label">
        <label for = "book_name">Book name:</label>
      </div>
      <div class="col-sm-10">
        <%= text_field 'book', 'name', required: true, class: 'form-control form-control-lg' %>
      </div>
    </div>
    <div class="mb-3 row">
      <div class="col-sm-2 col-form-label">
        <label for = "book_genre_id">Genres:</label>
      </div>
      <div class="col-sm-10">
        <%= collection_select(:book, :genre_id, @genres, :id, :name, { prompt: true }, { class: 'form-select form-select-lg' }) %>
      </div>
    </div>
    <div class="mb-3 row">
      <div class="col-sm-2 col-form-label">
        <label for = "author_ids">Authors:</label>
      </div>
      <div class="col-sm-10">
        <%= collection_select(:book, :author_ids, @authors, :id, :name, {}, { multiple: true, required: true, class: 'form-select form-select-lg' }) %>
      </div>
    </div>
    <div class="mb-3 row">
      <div class="col-sm-2 col-form-label">
        <label>Photo:</label>
      </div>
      <div class="col-sm-10">
        <%= file_field 'book', 'picture', required: true, class: 'form-control' %>
      </div>
    </div>
    <%= submit_tag "Update", class: 'btn btn-primary btn-md' %>
  <% end %>
  <%= link_to 'Back to library', { action: 'index' } %>
</div>

app/views/books/index.html.erb
<% provide :page_title, 'Books' %>
<% currently_at 'Home' %>
<h1 class="mb-4">Welcome, to library</h1>
<p>These are the current books in our system</p>
<p>
  <% if policy(Book).create? %>
    <%= button_to "Add new book", new_book_path, :id => "open-contacts-dialog-btn",
    :class => 'btn btn-primary btn-md', :method => :get %>
  <% end %>
</p>
<% @books_by_genres.each do |genre| %>
  <% next unless genre[:books].present? %>
  <div class="mb-4">
    <h2 class="mb-4"><%= genre[:name] %></h2>
    <div class="row row-cols-1 row-cols-md-5 g-4 mb-4">
      <% genre[:books].each do |book| %>
        <div class="col">
          <div class="card" style="max-width: 400px;">
            <% if book.picture.present? %>
              <%= image_tag book.picture, class:"card-img-top", size: "460x280", style: "object-fit: contain;" %>
            <% end %>
            <div class="card-body">
              <h5 class="mb-3"><%= book.name %></h5>
              <div>
                <%= link_to "Show", book_path(book), class: 'btn btn-secondary btn-sm', :method => :get %>
                <% if policy(book).edit? %>
                  <%= link_to "Edit",  edit_book_path(book), class: 'btn btn-secondary btn-sm', :method => :get %>
                <% end %>
                <% if policy(book).destroy? %>
                  <%= link_to "Destroy", book_path(book), class: 'btn btn-danger btn-sm', data: {method: :delete, confirm: "Are you sure?"} %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/books/new.html.erb
<% currently_at 'Home' %>
<div class="container-sm">
  <h1 class="mb-4">Add new book</h1>
  <%= form_tag({:action => 'create'}, multipart: true) do %>
    <div class="mb-3 row">
      <div class="col-sm-2 col-form-label">
        <label for = "book_name">Book name:</label>
      </div>
      <div class="col-sm-10">
        <%= text_field 'book', 'name', required: true, class: 'form-control form-control-lg' %>
      </div>
    </div>
    <div class="mb-3 row">
      <div class="col-sm-2 col-form-label">
        <label for = "book_genre_id">Genres:</label>
      </div>
      <div class="col-sm-10">
        <%= collection_select(:book, :genre_id, @genres, :id, :name, { required: true }, { class: 'form-control form-control-lg' }) %>
      </div>
    </div>
    <div class="mb-3 row">
      <div class="col-sm-2 col-form-label">
        <label for = "author_ids">Authors:</label>
      </div>
      <div class="col-sm-10">
        <%= collection_select(:book, :author_ids, @authors, :id, :name, {}, { multiple: true, required: true, class: 'form-control form-control-lg' }) %>
      </div>
    </div>
    <div class="mb-3 row">
      <div class="col-sm-2 col-form-label">
        <label>Photo:</label>
      </div>
      <div class="col-sm-10">
        <%= file_field 'book', 'picture', required: true, class: 'form-control' %>
      </div>
    </div>
    <%= submit_tag "Create", class: 'btn btn-primary btn-md' %>
  <% end %>
  <%= link_to 'Back to library', {:action => 'index'} %>
</div>

app/views/books/show.html.erb
<% currently_at 'Home' %>
<p>
  <%= image_tag @book.picture, class:"img-thumbnail", :style => "width: 500px" %>
</p>
<h1 class="mb-4"><%= @book.name %></h1>
<h3 class="mb-4">Authors: 
  <%= @book.authors.map { |author| link_to author.name, author }.join(', ').html_safe %>
</h3>

app/views/genres/edit.html.erb
<% currently_at 'Genres' %>
<div class="container-sm">
  <h1 class="mb-4"> Edit genre</h1>
  <%= form_tag genre_path(@genre), method: :put do %>
    <div class="mb-3 row">
      <div class="col-sm-2 col-form-label">
        <label for = "genre_name">Genre name:</label>
      </div>
      <div class="col-sm-10">
        <%= text_field 'genre', 'name', class: 'form-control form-control-lg' %>
      </div>
    </div>
    <div class="mb-3 row">
      <div class="col-sm-2 col-form-label">
        <label for = "genre_book_ids">Books:</label>
      </div>
      <div class="col-sm-10">
        <%= collection_select(:genre, :book_ids, @books, :id, :name, {}, {multiple: true, class: 'form-select form-select-lg'}) %>
      </div>
    </div>
    <%= submit_tag "Update", class: 'btn btn-primary btn-md' %>
  <% end %>
</div>

app/views/genres/index.html.erb
<% if policy(@genres).index? %>
  <% provide :page_title, 'Genres' %>
  <% currently_at 'Genres' %>
  <h1 class="mb-4">Genres:</h1>
  <div class="row row-cols-1 row-cols-md-5 g-4 mb-4">
    <% @genres.each do |genres| %>
      <div class="col">
        <div class="card" style="width: 300px;">
          <h2 class="mb-4 card-header"><%= genres.name %></h2>
          <div class="card-body">
            <%= link_to "Show", genre_path(genres), class: 'btn btn-secondary btn-sm', :method => :get %>
            <% if policy(genres).edit? %>
              <%= link_to "Edit",  edit_genre_path(genres), class: 'btn btn-secondary btn-sm', :method => :get %>
            <% end %>
            <% if policy(genres).destroy? %>
              <%= link_to "Destroy", genre_path(genres), class: 'btn btn-danger btn-sm', data: {method: :delete, confirm: "Are you sure?"} %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <% if policy(@genres).create? %>
    <%= button_to "Add new genre", new_genre_path, :id => "open-contacts-dialog-btn",
    :class => 'btn btn-primary btn-md', :method => :get %>
  <% end %>
<% end %>

app/views/genres/new.html.erb
<% currently_at 'Genres' %>
<div class="container-sm">
  <h1 class="mb-4">New genre</h1>
  <%= form_tag({:action => 'create'}, multipart: true) do %>
    <div class="mb-3 row">
      <div class="col-sm-2 col-form-label">
        <label for = "genre_name">Genre name:</label>
      </div>
      <div class="col-sm-10">
        <%= text_field 'genre', 'name', required: true%>
      </div>
    </div>
    <%= submit_tag "Create", class: 'btn btn-primary btn-md' %>
  <% end %>
</div>

app/views/genres/show.html.erb
<% currently_at 'Genres' %>
<h1 class="mb-4"><%= @genre.name%></h1>
<h2 class="mb-4">Books:
  <%= @genre.books.map { |book| link_to book.name, book }.join(', ').html_safe %>
</h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title><%= full_title(yield(:page_title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= yield :main_menu %>
    <main style="margin: 20px 80px">
      <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_menu.html.erb
<%= provide :main_menu do %>
  <header class="p-3 bg-dark text-white">
    <div class="container">
      <nav class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li><%= nav_tab 'Home', root_path, class: 'nav-link px-2', current_page: current_page %></li>
          <li><%= nav_tab 'Authors', authors_path, class: 'nav-link px-2', current_page: current_page %></li>
          <% if policy(Genre).index? %>
            <li><%= nav_tab 'Genres', genres_path, class: 'nav-link px-2', current_page: current_page %></li>
          <% end %>
          <% if policy(Admin).index? %>
            <li><%= nav_tab 'Admins', admins_path, class: 'nav-link px-2', current_page: current_page %></li>
          <% end %>
        </ul>
        <ul class="nav col-12 col-lg-auto mb-2 mb-md-0">
          <% if user_signed_in? %>
            <li class="dropdown">
              <%= nav_tab current_user.name, '#',
                class: 'nav-link px-2 dropdown-toggle',
                data: {"bs-toggle": 'dropdown'}, current_page: current_page %>
              <ul class="dropdown-menu">
                <li>
                  <%= link_to 'Log out', session_path,
                    class: 'dropdown-item', data: {method: :delete} %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= nav_tab 'Log In', new_session_path,
              class: 'nav-link px-2', current_page: current_page %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </header>
<% end %>